In [84]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


##Introduction to Tensors

###Scalars

In [85]:
Scalar = torch.tensor(7)
Scalar

tensor(7)

In [86]:
Scalar.ndim

0

In [87]:
# Get Tensor back as Python int
Scalar.item()

7

In [88]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [89]:
vector.ndim

1

In [90]:
vector.shape

torch.Size([2])

In [91]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [92]:
MATRIX.ndim

2

In [93]:
MATRIX[1]

tensor([ 9, 10])

In [94]:
MATRIX.shape

torch.Size([2, 2])

In [95]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [96]:
TENSOR.ndim

3

In [97]:
TENSOR.shape

torch.Size([1, 3, 3])

In [98]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why Random Tensors?

Random tensors are important because the way many neural learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers ---> look at data  ---> update random numbers ---> look at data ---> update random numbers


In [99]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4872, 0.7618, 0.4219, 0.2652],
        [0.3451, 0.4289, 0.4877, 0.7477],
        [0.0539, 0.5539, 0.4520, 0.2163]])

In [100]:
random_tensor.ndim

2

In [101]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224))  # height, width, colour channels channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [102]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [104]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
ones.dtype

torch.float32

In [106]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors - like

In [107]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tenors datarypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [109]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (eg - float32 or float16)
                               device = None, # what device your tensor on
                               requires_grad = False) # whether or not track gradiets with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [110]:
float_32_tensor.dtype

torch.float32

In [111]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [112]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [113]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [114]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting inforamtion from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [115]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3620, 0.9823, 0.7665, 0.8883],
        [0.8032, 0.0859, 0.2382, 0.6277],
        [0.7900, 0.8672, 0.6701, 0.9424]])

In [116]:
# Find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3620, 0.9823, 0.7665, 0.8883],
        [0.8032, 0.0859, 0.2382, 0.6277],
        [0.7900, 0.8672, 0.6701, 0.9424]])
Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operation include:

* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication

In [117]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [118]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [119]:
tensor

tensor([1, 2, 3])

In [120]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [121]:
# Try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [122]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication n neural networks and deep learning:
1. Element - wise multiplication
2. Matrix multiplication(dot product)

In [123]:
# Element wise multiplcation
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [124]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [125]:
tensor @ tensor


tensor(14)

In [126]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [127]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.62 ms, sys: 0 ns, total: 2.62 ms
Wall time: 5.66 ms


In [128]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 121 µs, sys: 14 µs, total: 135 µs
Wall time: 140 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [129]:
# Shapes for Matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)


In [130]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

1 To fix our tensor shape issues, we can manipulate the shape of ones of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [131]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [132]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [133]:
# The Matrix multiplication operation works when tensor_B is transposed

print(f"Original shape of A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <---- inner dimension must match")
print(f"Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shape of A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <---- inner dimension must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [134]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [135]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [136]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [137]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [138]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [139]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [140]:
# Find the position in tensor that has the minimum value with the argmin()   ---> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [141]:
x[0]

tensor(0)

In [142]:
# Find the position in tensor that has the maximum value with the argmax()
x.argmax()

tensor(9)

In [143]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensorof certain shape but keep the samee memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [144]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [145]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [146]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [147]:
# Changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [148]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [149]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [150]:
x_reshaped.shape

torch.Size([1, 9])

In [151]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [152]:
x_reshaped.squeeze().shape

torch.Size([9])

In [153]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size = (224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [154]:
x_original[0, :, 0]

tensor([4.3376e-01, 4.4664e-01, 8.2029e-01, 8.5918e-01, 4.8199e-01, 8.4044e-01,
        6.1670e-01, 5.3567e-01, 4.0272e-01, 8.8363e-02, 8.0865e-01, 8.0655e-01,
        9.6604e-01, 9.6148e-01, 2.3320e-01, 4.4039e-01, 8.0957e-01, 5.2263e-01,
        4.0575e-01, 6.7482e-01, 1.3059e-01, 9.0218e-01, 3.0118e-01, 7.3869e-01,
        3.3376e-02, 6.7161e-01, 4.4314e-01, 3.2358e-01, 6.4938e-01, 5.5798e-01,
        5.2206e-01, 1.7680e-01, 5.5830e-01, 8.0333e-01, 4.4796e-01, 4.7018e-01,
        1.6375e-01, 5.3270e-02, 8.2855e-02, 2.4548e-01, 9.6477e-01, 1.2480e-01,
        6.8719e-02, 7.1658e-01, 8.2096e-01, 7.0683e-01, 8.5786e-01, 4.9325e-02,
        6.7276e-01, 5.3947e-01, 4.6018e-01, 6.6209e-01, 9.3971e-01, 1.1575e-02,
        2.5286e-01, 4.0914e-01, 6.4727e-02, 9.5092e-01, 2.8416e-01, 3.9341e-01,
        9.1883e-01, 9.9557e-01, 5.8056e-01, 2.8957e-01, 1.0624e-01, 7.3935e-01,
        9.5503e-01, 3.8692e-01, 6.2746e-03, 2.9727e-01, 2.5077e-01, 3.6859e-01,
        7.1758e-01, 3.4149e-01, 8.1155e-

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing in Numpy

In [155]:
# Create a tensor
import torch
x  =  torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [156]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [157]:
# Lets index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [158]:
# Lets index on the mostt inner bracket
x[0][0][0]
x[0][2][2]

tensor(9)

In [159]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [160]:
# Get all values of 0th and 1st dimensions but only index 1 and 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [161]:
# Get all values of the 0 of 0th dimension but only the 1 index value of 1st and 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors and Numpy

Numpy is a popular scientific python numerical computing library.

And because of this, PyTorch has a functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.NumPy()'

In [162]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [163]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [165]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [166]:
numpy_tensor.dtype

dtype('float32')

In [167]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor +  1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers --> tensor operation --> update random numbers to try and make them better representations of the data --> again --> again --> again...`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [168]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9607, 0.7503, 0.3395, 0.2903],
        [0.1684, 0.6906, 0.1114, 0.7607],
        [0.3903, 0.9429, 0.5050, 0.6060]])
tensor([[0.9554, 0.7876, 0.2877, 0.0548],
        [0.5293, 0.8610, 0.8601, 0.9025],
        [0.3707, 0.9391, 0.3326, 0.7852]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [170]:
# Lets make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#